### ISSUE TITLE
Best practice for conditional / chaining module queries?

### ISSUE THREAD

**Issue by OliverJEvans** [CyCraft/magnetar#104]
I'm trying to find a nice way to conditional add / chain module queries.

I have a filteredResults computed property, inside I have a module where I have a module and do some inital querying. I then want to chain amultiple additional queries based on a condition.

```
filteredItems() {
  const filteredItemsModule = itemsModule.where('inStock', '==', true);

  if(this.priceMax) {
    filteredItemsModule.where('price', '<=', this.priceFilter.max);
  }

  filteredItemsModule.fetch();

  return filteredItemsModule.data.values();
}
```

However this just results in filteredItems being the inStock items (the original query) and the second price query is ignored.

The console shows the query as `db.collection('items').where('inStock', '==', true)` (no price query). 

It seems once one query has been added to a module, you can't add another unless its chained directly after the first? 

```
  // can't do this
  filteredItemsModule.where("inStock", "==", true);
  filteredItemsModule.where("price", "<=", this.priceFilter.max);
  filteredItemsModule.where("price", ">=", this.priceFilter.min);
```
        
```
  // can only do this
  filteredItemsModule
    .where("inStock", "==", true)
    .where("price", "<=", this.priceFilter.max)
    .where("price", ">=", this.priceFilter.min);
```

Any recommendations please?

**Comment by mesqueeb** [comment]
Hello, in order to save the filter you must make it a new variable.
This is to prevent filter pollution when you don't expect it.

see this snippet where i reassign the instance in a `let`
```ts
filteredItems() {
  let filteredItemsModule = itemsModule.where('inStock', '==', true);

  if(this.priceMax) {
    filteredItemsModule = filteredItemsModule.where('price', '<=', this.priceFilter.max);
  }

  filteredItemsModule.fetch();

  return filteredItemsModule.data.values();
}
```
PS, don't forget to force fetch in case you need it. `fetch({ force: true })` otherwise if it finds even 1 doc in your local state, it will not do an api call (optimistic by default)
