### ISSUE TITLE
Collection Query by Firestore timestamp

### ISSUE THREAD

**Issue by loverziyu** [CyCraft/magnetar#44]
Hi there Luca, thank you for your Magnetar, it is a wonderful state management for my firestore project.

Recently notice some problem/bug (not sure about it)
If I would like to fetch some collection with time/date query, 
-> magnetar.collection(`doc`).where('date', '>', new Date('1 May 2021')).fetch()

it will return nothing even the document date is in range of the query.

Thank you

**Comment by mesqueeb** [comment]
Try `fetch({ force: true })`

If that works then let's discuss further and see if we can improve stuff.

**Comment by loverziyu** [comment]
![BUG](https://user-images.githubusercontent.com/5509348/120889093-2c5cb300-c62e-11eb-8396-9191541b9be0.PNG)

Thanks for the reply,
I had tried the mentioned solution but still the same,
Attached photo of comparing native firestore SDK with the result of Magnetar

**Comment by mesqueeb** [comment]
@loverziyu can you add me on Discord?
`Luca Ban [Mesqueeb]#4774`

**Comment by mesqueeb** [comment]
@loverziyu thanks for your patience.
Fixed in latest version `magnetar@0.5.6`

<sub>--<br />Magnetar was made with 💜 by Luca Ban.<br />You cannot sponsor every project, but next time you do, think of <a href="https://github.com/sponsors/mesqueeb">this one</a> for its prolonged maintenance.</sub>
