### ISSUE TITLE
What license is/will this be available under?

### ISSUE THREAD

**Issue by wifisher** [CyCraft/magnetar#56]
I would like to see the license information updated for this software.

I can't truly consider using it without first knowing the licensing details.

Thanks.

**Comment by mesqueeb** [comment]
@wifisher thanks I'm thinking of MIT I guess. I'll add it soon.

**Comment by wifisher** [comment]
The MIT license would be compatible with my needs if that is what you end up choosing.

Thanks.

**Comment by wifisher** [comment]
I would like to see the license added to this project soon before I commit to using it in my project. I need to be sure that the license is suitable for my needs before I can use it.

**Comment by mesqueeb** [comment]
@wifisher released in:

 - @magnetarjs/core@0.2.13
 - magnetar@0.4.15
 - @magnetarjs/plugin-firestore@0.3.15
 - @magnetarjs/plugin-simple-store@0.1.16
 - @magnetarjs/plugin-vue2@0.1.16
 - @magnetarjs/plugin-vue3@0.1.17
 - @magnetarjs/utils@0.1.16
