### ISSUE TITLE
Type '(payload: Partial<Pokemon>) => Pokemon' is not assignable to type 'OnAddedFn'

### ISSUE THREAD

**Issue by vdsbenoit** [CyCraft/magnetar#76]
Hi @mesqueeb,

First of all, thanks a lot for the great work you have done here ! It is much appreciated 🙇‍♂️

I am trying to configure magnetar in a project I recently started with Vue 3. However, I am having trouble to make it work with TypeScript. To simplify my description, I am going to use [the example provided in your documentation](https://magnetar.cycraft.co/docs#setup-for-typescript).

When I try to transpile this snippet : 
````ts
export type Pokemon = { name: string, nickName?: string, id: string, level: number }

export function pokemonDefaults(payload: Partial<Pokemon>): Pokemon {
  const defaults: Pokemon = { name: '', nickName: '', id: '', level: 0 }

  return { ...defaults, ...payload }
}

// here is how you inject the Type: collection<Pokemon>
export const pokedexModule = magnetar.collection<Pokemon>('pokedex', {
  modifyPayloadOn: { insert: pokemonDefaults },
  modifyReadResponseOn: { added: pokemonDefaults },
})
````

I get this error:
````ts
ERROR in src/services/pokemon.ts:18:27
TS2322: Type '(payload: Partial<Pokemon>) => Pokemon' is not assignable to type 'OnAddedFn'.
  Types of parameters 'payload' and 'docData' are incompatible.
    Type 'Record<string, any> | undefined' is not assignable to type 'Partial<Pokemon>'.
      Type 'undefined' is not assignable to type 'Partial<Pokemon>'.
    16 | export const pokedexModule = magnetar.collection<Pokemon>('pokedex', {
    17 |   modifyPayloadOn: { insert: pokemonDefaults },
  > 18 |   modifyReadResponseOn: { added: pokemonDefaults },
       |                           ^^^^^
    19 | })
    20 |
````

Do you have an idea what could have gone wrong? 

Here is my config 
````
node 16.13.1
magnetar 0.5.4
typescript 4.6.2
````

**Comment by mesqueeb** [comment]
@vdsbenoit thanks for finding this!

So I have typed the `modifyReadResponseOn.added` function kind of weirdly:
```ts
/**
 * Can be used to modify docs that come in from 'stream' or 'fetch' actions, before they are added to your store data. When returning `undefined` they will be discarded & won't be added to the store data.
 */
export type OnAddedFn = (docData: Record<string, any> | undefined, docMetadata: DocMetadata) => Record<string, any> | void
```
see source code at:
- https://github.com/cycraft/magnetar/blob/production/packages/core/src/types/modifyReadResponse.ts/#L3-L7

But I don't think we should ever execute the `modifyReadResponseOn.added` fn when the payload is `undefined`.

Changing my underlying type to this will fix the issue:

```ts
/**
 * Can be used to modify docs that come in from 'stream' or 'fetch' actions, before they are added to your store data. When returning `undefined` they will be discarded & won't be added to the store data.
 */
export type OnAddedFn = (docData: Record<string, any>, docMetadata: DocMetadata) => Record<string, any> | void
```

So I will do this somewhere this week after checking this won't cause issues.

In the meanwhile you can fix the issue on your end with a workaround of adding a simple `?` in the defaults fn payload like so:

```js
export function pokemonDefaults(payload?: Partial<Pokemon>): Pokemon {
  const defaults: Pokemon = { name: '', nickName: '', id: '', level: 0 }

  return { ...defaults, ...payload }
}
```
see the `payload?: ` : ) that's the workaround that should work for now

**Comment by vdsbenoit** [comment]
Thanks a lot for your quick reply ! I'll try that

**Comment by mesqueeb** [comment]
@vdsbenoit you can now define the type of your document when inserting separately from the type of your module doc.

```ts
 const pokedexModule = magnetar.collection<Pokemon, { insert: Partial<Pokemon> }>('pokedex', 
  modifyPayloadOn: { insert: pokemonDefaults },
  modifyReadResponseOn: { added: pokemonDefaults },
})
```

this will make it so executing `pokedexModule.insert({ name: 'bulbasaur' })` won't cause any issue if this is only a partial of your document.

Does this help you further?

**Comment by mesqueeb** [comment]
@vdsbenoit on `magnetar@0.8.3` I have changed the logic so `modifyReadResponseOn.added` is no longer executed when a fetch call returns no document.

This means that there is no possibility that the payload of `modifyReadResponseOn.added` is `undefined` anymore.

This means that the documentation example is now possible without type issues.

workaround: `pokemonDefaults(payload?: Partial<Pokemon>):` is no longer needed, you can use `pokemonDefaults(payload: Partial<Pokemon>):` without the `?` again! 🎉 

let me know if you have any further issues.

**Comment by vdsbenoit** [comment]
Hi,

I'm diving into my side project again (it's for an event that takes place once a year). I upgraded magnetar from 0.5.4 to 0.11.4. I confirm the issue is resolved! Thanks again for your support !
