### ISSUE TITLE
Inconsistency in documentation links 

### ISSUE THREAD

**Issue by rustamd** [CyCraft/magnetar#93]
There's some inconsistency with links in documentation. 

Generated links ([here I believe](https://github.com/CyCraft/planetar/blob/c4e94adee17e6be9be802e4484da27db929815a8/packages/doc-builder/src/components/TableOfContents.vue#L114)) point to `https://magnetar.cycraft.co/#TOPIC`, but when actual link in docs is clicked ([using router.push()](https://github.com/CyCraft/planetar/blob/c4e94adee17e6be9be802e4484da27db929815a8/packages/doc-builder/src/components/TableOfContents.vue#L214)) it redirects to `https://magnetar.cycraft.co/docs#TOPIC`

This works ok when navigating from inside docs, but breaks when you try to copy link [https://magnetar.cycraft.co/#about](https://magnetar.cycraft.co/#about)

I haven't really dug in to see why `computedTOC` is missing `/docs`, perhaps @mesqueeb can chime in as he's more 'familiar' with **Planetar**

**Comment by mesqueeb** [comment]
@rustamd thanks for the report!
I plan to rewrite the docs with the new vitepress framework. : )

If all goes according to plan, new docs should be up in about 2 weeks!! I'll come close this issue after they're released.

**Comment by rustamd** [comment]
Awesome! Looking forward to the upgrade.
